Assignment-4

In [2]:
#Importing require library
import pandas as pd
import selenium
import re
from selenium.webdriver.support.ui import WebDriverWait
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException,TimeoutException
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
import time
import requests

Que1.- Scrape the details of most viewed videos on YouTube from Wikipedia:Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/ You need to find following details:


A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [3]:
# connect to the webdriver
driver=driver=webdriver.Chrome(r"chromedriver.exe")
driver.maximize_window()

In [4]:
#searching on google
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [5]:
# creating empty list for scraping the data

Rank = []
Name = []
Artist = []
Date = []
Views = []

In [6]:
# scraping Required the data
rank=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[1]')
Rank=[i.text for i in rank]

name=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[2]')
Name=[i.text for i in name]

artist=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[3]')
Artist=[i.text for i in artist]

upload_date=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[5]')
Upload_date=[i.text for i in upload_date]

views=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[4]')
Views=[i.text for i in views]

In [7]:
#Creat Data Frame
df=pd.DataFrame({
    'Rank':Rank[0:30],
    'Name':Name[0:30],
    'Artist':Artist[0:30],
    'Upload_date':Upload_date[0:30],
    'Views':Views[0:30]
})
df

,Rank,Name,Artist,Upload_date,Views
0,1.,"""Baby Shark Dance""[4]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",12.00
1,2.,"""Despacito""[7]",Luis Fonsi,"January 12, 2017",8.05
2,3.,"""Johny Johny Yes Papa""[14]",LooLoo Kids,"October 8, 2016",6.57
3,4.,"""Bath Song""[15]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.89
4,5.,"""Shape of You""[16]",Ed Sheeran,"January 30, 2017",5.88
5,6.,"""See You Again""[18]",Wiz Khalifa,"April 6, 2015",5.74
6,7.,"""Phonics Song with Two Words""[23]",ChuChu TV,"March 6, 2014",5.08
7,8.,"""Uptown Funk""[24]",Mark Ronson,"November 19, 2014",4.79
8,9.,"""Wheels on the Bus""[25]",Cocomelon – Nursery Rhymes,"May 24, 2018",4.77
9,10.,"""Learning Colors – Colorful Eggs on a Farm""[26]",Miroshka TV,"February 27, 2018",4.76
10,11.,"""Gangnam Style""[27]",Psy,"July 15, 2012",4.64
11,12.,"""Masha and the Bear – Recipe for Disaster""[32]",Get Movies,"January 31, 2012",4.52
12,13.,"""Dame Tu Cosita""[33]",El Chombo,"April 5, 2018",4.18
13,14.,"""Sugar""[34]",Maroon 5,"January 14, 2015",3.80
14,15.,"""Roar""[35]",Katy Perry,"September 5, 2013",3.70
15,16.,"""Counting Stars""[36]",OneRepublic,"May 31, 2013",3.70
16,17.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.67
17,18.,"""Sorry""[38]",Justin Bieber,"October 22, 2015",3.62
18,19.,"""Thinking Out Loud""[39]",Ed Sheeran,"October 7, 2014",3.53
19,20.,"""Baa Baa Black Sheep""[40]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.46
20,21.,"""Dark Horse""[41]",Katy Perry,"February 20, 2014",3.42
21,22.,"""Waka Waka (This Time for Africa)""[42]",Shakira,"June 4, 2010",3.40
22,23.,"""Faded""[43]",Alan Walker,"December 3, 2015",3.38
23,24.,"""Let Her Go""[44]",Passenger,"July 25, 2012",3.36
24,25.,"""Girls Like You""[45]",Maroon 5,"May 31, 2018",3.35
25,26.,"""Perfect""[46]",Ed Sheeran,"November 9, 2017",3.33
26,27.,"""Bailando""[47]",Enrique Iglesias,"April 11, 2014",3.31
27,28.,"""Lean On""[48]",Major Lazer,"March 22, 2015",3.31
28,29.,"""Humpty the train on a fruits ride""[49]",Kiddiestv Hindi – Nursery Rhymes & Kids Songs,"January 26, 2018",3.26
29,30.,"""Lakdi Ki Kathi""[50]",Jingle Toons,"June 14, 2018",3.24

Que.2- Scrape the details team India’s international fixtures from bcci.tv.Url = https://www.bcci.tv/.You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code

In [13]:
#connect to webdriver
driver_2=webdriver.Chrome(r'chromedriver.exe')
driver_2.maximize_window()

#get webpage
url=("https://www.bcci.tv/")
driver_2.get(url)
time.sleep(2)

In [14]:
#clicking on menu
button= driver_2.find_element(By.XPATH,'//span[@class = "menu-icon__line menu-icon__line-right"]').get_attribute('href')

In [15]:
#selecting International
International= driver_2.find_element(By.XPATH,'//a[@class = "nav-link "]').click()

In [16]:
#clicking on dropdown
Select= driver_2.find_element(By.XPATH,'/html/body/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div[3]/div/div[1]').click()

In [17]:
#selecting ODI
OdI= driver_2.find_element(By.XPATH,'/html/body/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div[3]/div/div[2]/div[3]').click()

In [18]:
Match_title= []
Series= []
Place= []
Date= []
Time= []

#scraping Match Title
try:
    Match_title_tag= driver_2.find_elements(By.XPATH,"//div[@class='fixture-card-top']/h5[2]")
    for i in Match_title_tag:
        Match_title.append(i.text)
except NoSuchElementException as e:
    Match_title.append("--")

#scraping Series
try:
    Series_tag= driver_2.find_elements(By.XPATH,"//div[@class='fixture-card-bottom']")
    for i in Series_tag:
        Series.append(i.text.split("-")[0])
except NoSuchElementException as e:
    Series.append("--")
    
#scraping Place
try:
    Place_tag= driver_2.find_elements(By.XPATH,"//div[@class='fixture-card-bottom']")
    for i in Place_tag:
        Place.append(i.text.split("-")[1].replace("\n",","))
except NoSuchElementException as e:
    Place.append("--") 

#scraping Date
try:
    Date_tag= driver_2.find_elements(By.XPATH,"//div[@class='match-card-left match-schedule']")
    for i in Date_tag:
        Date.append(i.text)
except NoSuchElementException as e:
    Date.append("--")

#scraping Time   
try:
    Time_tag= driver_2.find_elements(By.XPATH,"//div[@class='match-card-right match-schedule ']")
    for i in Time_tag:
        Time.append(i.text)
except NoSuchElementException as e:
    Time.append("--")

#printing length
print(len(Match_title),len(Series),len(Place),len(Date),len(Time))

#creating Dataframe
international_fixtures=pd.DataFrame({"Match_title":Match_title,"Series":Series,"Place":Place,"Date":Date,"Time":Time})
international_fixtures

8 8 8 8 8

,Match_title,Series,Place,Date,Time
0,SRI LANKA TOUR OF INDIA ODI SERIES 2022-23,1st ODI,"Barsapara Cricket Stadium, Guwahati,Match Centre",10 JAN 2023,1:30 PM IST
1,SRI LANKA TOUR OF INDIA ODI SERIES 2022-23,2nd ODI,"Eden Gardens, Kolkata,Match Centre",12 JAN 2023,1:30 PM IST
2,SRI LANKA TOUR OF INDIA ODI SERIES 2022-23,3rd ODI,"Greenfield International Stadium, Thiruvanant...",15 JAN 2023,1:30 PM IST
3,NEW ZEALAND TOUR OF INDIA ODI SERIES 2022-23,1st ODI,"Rajiv Gandhi International Stadium, Hyderabad...",18 JAN 2023,1:30 PM IST
4,NEW ZEALAND TOUR OF INDIA ODI SERIES 2022-23,2nd ODI,Shaheed Veer Narayan Singh International Cric...,21 JAN 2023,1:30 PM IST
5,NEW ZEALAND TOUR OF INDIA ODI SERIES 2022-23,3rd ODI,"Holkar Cricket Stadium, Indore,Match Centre",24 JAN 2023,1:30 PM IST
6,AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23,1st ODI,"Wankhede Stadium, Mumbai,Match Centre",17 MAR 2023,1:30 PM IST
7,AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23,2nd ODI,Dr YS Rajasekhara Reddy ACA,19 MAR 2023,1:30 PM IST

q.3 Scrape the details of State-wise GDP of India from statisticstime.com.

Url = http://statisticstimes.com/

You have to find following details:

A) Rank

B) State

C) GSDP(18-19)- at current prices

D) GSDP(19-20)- at current prices

E) Share(18-19)

F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code.

In [41]:
# connect to webdriver
driver4=webdriver.Chrome(r"chromedriver.exe")
driver4.maximize_window()

# search on google is https://www.statisticstimes.com/
driver4.get("https://www.statisticstimes.com/")


# for click
Economy=driver4.find_element(By.XPATH,'//div[@class="navbar"]/div[2]/button')
Economy.click()
time.sleep(3)

# for click
India=driver4.find_element(By.XPATH,'//div[@class="navbar"]/div[2]/div/a[3]')
India.click()
time.sleep(6)

# for click
India_GDP=driver4.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
India_GDP.click()
time.sleep(3)

In [42]:
# Fetch all Require Data

rank=driver4.find_elements(By.XPATH,'//div[@class="dataTables_wrapper"]/table/tbody/tr/td[1]')
Rank=[i.text for i in rank]

state=driver4.find_elements(By.XPATH,'//div[@class="dataTables_wrapper"]/table/tbody/tr/td[2]')
State=[i.text for i in state]

gSDP_18_19=driver4.find_elements(By.XPATH,'//div[@class="dataTables_wrapper"]/table/tbody/tr/td[4]')
GSDP_18_19=[i.text for i in gSDP_18_19]

gSDP_19_20=driver4.find_elements(By.XPATH,'//div[@class="dataTables_wrapper"]/table/tbody/tr/td[3]')
GSDP_19_20=[i.text for i in gSDP_19_20]

share_18_19=driver4.find_elements(By.XPATH,'//div[@class="dataTables_wrapper"]/table/tbody/tr/td[5]')
Share_18_19=[i.text for i in share_18_19]

gdp=driver4.find_elements(By.XPATH,'//div[@class="dataTables_wrapper"]/table/tbody/tr/td[6]')
GDP=[i.text for i in gdp]


#Creat DataFrame
df=pd.DataFrame({
    'Rank':Rank[0:33],
    'State':State[0:33],
    'GSDP_18_19':GSDP_18_19[0:33],
    'GSDP_19_20':GSDP_19_20[0:33],
    'Share_18_19':Share_18_19[0:33],
    'GDP':GDP[0:33]
})
df

   Rank                      State GSDP_18_19 GSDP_19_20 Share_18_19      GDP
0     1                Maharashtra  2,632,792          -      13.94%  399.921
1     2                 Tamil Nadu  1,630,208  1,845,853       8.63%  247.629
2     3              Uttar Pradesh  1,584,764  1,687,818       8.39%  240.726
3     4                    Gujarat  1,502,899          -       7.96%  228.290
4     5                  Karnataka  1,493,127  1,631,977       7.91%  226.806
5     6                West Bengal  1,089,898  1,253,832       5.77%  165.556
6     7                  Rajasthan    942,586  1,020,989       4.99%  143.179
7     8             Andhra Pradesh    862,957    972,782       4.57%  131.083
8     9                  Telangana    861,031    969,604       4.56%  130.791
9    10             Madhya Pradesh    809,592    906,672       4.29%  122.977
10   11                     Kerala    781,653          -       4.14%  118.733
11   12                      Delhi    774,870    856,112       4.10%  117.703
12   13                    Haryana    734,163    831,610       3.89%  111.519
13   14                      Bihar    530,363    611,804       2.81%   80.562
14   15                     Punjab    526,376    574,760       2.79%   79.957
15   16                     Odisha    487,805    521,275       2.58%   74.098
16   17                      Assam    315,881          -       1.67%   47.982
17   18               Chhattisgarh    304,063    329,180       1.61%   46.187
18   19                  Jharkhand    297,204    328,598       1.57%   45.145
19   20                Uttarakhand    245,895          -       1.30%   37.351
20   21            Jammu & Kashmir    155,956          -       0.83%   23.690
21   22           Himachal Pradesh    153,845    165,472       0.81%   23.369
22   23                        Goa     73,170     80,449       0.39%   11.115
23   24                    Tripura     49,845     55,984       0.26%    7.571
24   25                 Chandigarh     42,114          -       0.22%    6.397
25   26                 Puducherry     34,433     38,253       0.18%    5.230
26   27                  Meghalaya     33,481     36,572       0.18%    5.086
27   28                     Sikkim     28,723     32,496       0.15%    4.363
28   29                    Manipur     27,870     31,790       0.15%    4.233
29   30                   Nagaland     27,283          -       0.14%    4.144
30   31          Arunachal Pradesh     24,603          -       0.13%    3.737
31   32                    Mizoram     22,287     26,503       0.12%    3.385
32   33  Andaman & Nicobar Islands          -          -           -        -

Q4. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used
Note: - From the home page you have to click on the trending option from Explore menu through code

In [49]:
driver_5=webdriver.Chrome('chromedriver.exe')
driver_5.maximize_window()
url=(" https://github.com/")
driver_5.get(url)
time.sleep(2)

In [50]:
# Clicking on explore sub menu
explore = driver_5.find_element(By.XPATH,'//li[@class = "mr-0 mr-lg-3 position-relative flex-wrap flex-justify-between flex-items-center border-bottom border-lg-bottom-0 d-block d-lg-flex flex-lg-nowrap flex-lg-items-center"][4]')
try:
    explore.click()
    time.sleep(5)
except ElementNotInteractableException:
    driver_5.get(explore.get_attribute('href'))

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//li[@class = "mr-0 mr-lg-3 position-relative flex-wrap flex-justify-between flex-items-center border-bottom border-lg-bottom-0 d-block d-lg-flex flex-lg-nowrap flex-lg-items-center"][4]"}
  (Session info: chrome=108.0.5359.125)
Stacktrace:
Backtrace:
	(No symbol) [0x00E7F243]
	(No symbol) [0x00E07FD1]
	(No symbol) [0x00CFD04D]
	(No symbol) [0x00D2C0B0]
	(No symbol) [0x00D2C22B]
	(No symbol) [0x00D5E612]
	(No symbol) [0x00D485D4]
	(No symbol) [0x00D5C9EB]
	(No symbol) [0x00D48386]
	(No symbol) [0x00D2163C]
	(No symbol) [0x00D2269D]
	GetHandleVerifier [0x01119A22+2655074]
	GetHandleVerifier [0x0110CA24+2601828]
	GetHandleVerifier [0x00F28C0A+619850]
	GetHandleVerifier [0x00F27830+614768]
	(No symbol) [0x00E105FC]
	(No symbol) [0x00E15968]
	(No symbol) [0x00E15A55]
	(No symbol) [0x00E2051B]
	BaseThreadInitThunk [0x775500F9+25]
	RtlGetAppContainerNamedObjectPath [0x77947BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77947B8E+238]

In [51]:
# Clicking on Trending under explore sub menu
trending = driver_5.find_element(By.XPATH,'//*[@href="/trending"]')
try:
    driver_5.get(trending.get_attribute('href'))
except ElementNotInteractableException:
    driver_5.get(trending.get_attribute('href'))

In [52]:
Repository_title= []
Repository_description= []
Contributors_count= []
Language_used= []
urls=[]

#Scraping title of repository
try:
    Repository_title_tag=driver_5.find_elements(By.XPATH,'//article[@class="Box-row"]/h1/a')
    for i in Repository_title_tag:
        Repository_title.append(i.text)
except NoSuchElementException:
    Repository_title.append('-')
    
#Scraping description of Repository
try:
    description=driver_5.find_elements(By.XPATH,'//article[@class="Box-row"]/p')
    for i in description:
        Repository_description.append(i.text)
except NoSuchElementException:
    Repository_description.append('-')

for i in [Repository_title_tag,description]:
    for j in i:
        if i ==Repository_title_tag:
            Repository_title.append(j.text)
            urls.append(j.get_attribute('href'))
        if i==description:
            Repository_description.append(j.text)
    
for url in urls:
    driver_5.get(url)
    driver_5.implicitly_wait(3)
    div_list=driver_5.find_elements(By.XPATH,'//div[@class="BorderGrid BorderGrid--spacious"]/div')
    #Scraping count of contributors   
    try:
        Contributors_count.append(((div_list[-2].text).split())[1])
    except:
        Contributors_count.append('-')
    #Scraping used language
    try:
        Language_used.append(((div_list[-1].text).split())[1::2])
    except:
        Language_used.append('-')
        
#printing length
len(Repository_title),len(Repository_description),len(Language_used),len(Contributors_count)

#creating Dataframe
github_trending=pd.DataFrame({"Repository_title":Repository_title[:25],"Repository_description":Repository_description[:25],"Language_used":Language_used[:25],"Contributors_count":Contributors_count[:25]})
github_trending

,Repository_title,Repository_description,Language_used,Contributors_count
0,LAION-AI / Open-Assistant,OpenAssistant is a chat-based assistant that u...,"[Jupyter, 89.8%, 7.2%, 2.6%, 0.3%, 0.1%, 0.0%]",37
1,karpathy / nanoGPT,"The simplest, fastest repository for training/...",[Python],2
2,sczhou / CodeFormer,[NeurIPS 2022] Towards Robust Blind Face Resto...,"[Python, Cuda, C++]",3
3,DarkFlippers / unleashed-firmware,Flipper Zero Unleashed Firmware,"[C, Python, HTML, PHP, C++, Assembly]",191
4,ytdl-org / youtube-dl,Command-line program to download videos from Y...,"[Python, Other]",777
5,google / osv-scanner,Vulnerability scanner written in Go which uses...,"[Go, Other]",15
6,pola-rs / polars,"Fast multi-threaded, hybrid-streaming DataFram...","[Rust, Python, Other]",141
7,neonbjb / tortoise-tts,A multi-voice TTS system trained with an empha...,"[Python, HTML, Jupyter, 1.8%]",11
8,Developer-Y / cs-video-courses,List of Computer Science courses with video le...,"[75, 64]",No
9,dair-ai / Prompt-Engineering-Guide,🐙 Guide and resources for prompt engineering,"[3, Elvis, dominiksipowicz, Sip, Mihail]",-
10,Ebazhanov / linkedin-skill-assessments-quizzes,Full reference of LinkedIn answers 2022 for sk...,[Python],"1,269"
11,ocornut / imgui,Dear ImGui: Bloat-free Graphical User interfac...,"[C++, C, Objective-C++, Objective-C, GLSL, GDB]",313
12,AmruthPillai / Reactive-Resume,A one-of-a-kind resume builder that keeps your...,"[TypeScript, SCSS, JavaScript, Dockerfile, Kot...",84
13,PRQL / prql,PRQL is a modern language for transforming dat...,"[Rust, CSS, JavaScript, HTML, Java, Shell, Other]",35
14,A-poc / RedTeam-Tools,Tools and Techniques for Red Team / Penetratio...,[],Tools
15,jerryjliu / gpt_index,An index created by GPT to organize external i...,"[Python, Jupyter, 4.4%]",6
16,imDazui / Tvlist-awesome-m3u-m3u8,直播源相关资源汇总 📺 💯 IPTV、M3U —— 勤洗手、戴口罩，祝愿所有人百毒不侵,"[No, published]",No
17,aurae-runtime / aurae,Distributed systems runtime daemon written in ...,"[Rust, Nix, Shell, TypeScript, Makefile, Rende...",25
18,zlib-searcher / zlib-searcher,search zlib/libgen index to get ipfs_cid.,"[TypeScript, Rust, Shell, Python, Makefile, Do...",9
19,BrunoLevy / learn-fpga,"Learning FPGA, yosys, nextpnr, and RISC-V","[C++, Verilog, GLSL, C, Assembly, Makefile, Ot...",11
20,alist-org / alist,🗂️A file list program that supports multiple s...,"[Go, Other]",30
21,freeCodeCamp / freeCodeCamp,freeCodeCamp.org's open-source codebase and cu...,"[TypeScript, JavaScript, CSS, Shell, Dockerfil...","4,626"
22,Atlas-OS / Atlas,"🚀 An open-source modification of Windows 10, d...","[Batchfile, PowerShell]",18
23,SheerSt / pokewilds,PokeWilds - A Gen 2 Game/Engine using libGDX,[Assembly],8
24,jwasham / coding-interview-university,A complete computer science study plan to beco...,"[282, 271]",by

Q5 Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [80]:
# connect to webdriver
driver=webdriver.Chrome(r"chromedriver.exe")
driver.maximize_window()

# search on google is https://www.billboard.com/
driver.get("https://www.billboard.com/")

# for click
Click1=driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]/a')
Click1.click()
time.sleep(3)

# for click
Click2=driver.find_element(By.XPATH,'/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[3]/a')
Click2.click()
time.sleep(3)

ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (631, 942)
  (Session info: chrome=108.0.5359.125)
Stacktrace:
Backtrace:
	(No symbol) [0x00E7F243]
	(No symbol) [0x00E07FD1]
	(No symbol) [0x00CFD04D]
	(No symbol) [0x00D328B9]
	(No symbol) [0x00D308CC]
	(No symbol) [0x00D2E4CB]
	(No symbol) [0x00D2D164]
	(No symbol) [0x00D232A6]
	(No symbol) [0x00D4858C]
	(No symbol) [0x00D22BFF]
	(No symbol) [0x00D48804]
	(No symbol) [0x00D5C9EB]
	(No symbol) [0x00D48386]
	(No symbol) [0x00D2163C]
	(No symbol) [0x00D2269D]
	GetHandleVerifier [0x01119A22+2655074]
	GetHandleVerifier [0x0110CA24+2601828]
	GetHandleVerifier [0x00F28C0A+619850]
	GetHandleVerifier [0x00F27830+614768]
	(No symbol) [0x00E105FC]
	(No symbol) [0x00E15968]
	(No symbol) [0x00E15A55]
	(No symbol) [0x00E2051B]
	BaseThreadInitThunk [0x775500F9+25]
	RtlGetAppContainerNamedObjectPath [0x77947BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77947B8E+238]

In [83]:
#fetch require Data
song_name=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]//h3')
Song_name=[i.text for i in song_name]


artist_name=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[1]/span')
Artist_name=[i.text for i in artist_name]


last_week_rank=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[4]/span[1]')
Last_week_rank=[i.text for i in last_week_rank]


peak_rank=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[5]/span[1]')
Peak_rank=[i.text for i in peak_rank]


weeks_on_board=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[6]/span[1]')
Weeks_on_board=[i.text for i in weeks_on_board]


#Creat DataFrame
df=pd.DataFrame({
    'Song_name':Song_name,
    'Artist_name':Artist_name,
    'Last_week_rank':Last_week_rank,
    'Peak_rank':Peak_rank,
    'Weeks_on_board':Weeks_on_board
})
df

,Song_name,Artist_name,Last_week_rank,Peak_rank,Weeks_on_board
0,All I Want For Christmas Is You,Mariah Carey,1,1,27
1,Last Christmas,Wham!,3,2,23
2,Rockin' Around The Christmas Tree,Brenda Lee,2,2,20
3,Jingle Bell Rock,Bobby Helms,4,4,20
4,Kill Bill,SZA,5,5,2
...,...,...,...,...,...
195,What Christmas Means To Me,John Legend Featuring Stevie Wonder,-,91,8
196,Gatubela,Karol G x Maldy,-,23,16
197,Candy,NCT DREAM,-,198,1
198,Que Agonia,Yuridia & Angela Aguilar,-,192,3
199,Metamorphosis,INTERWORLD,-,200,1

Q9.Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location

Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [84]:
# connect to webdriver
driver=webdriver.Chrome(r"chromedriver.exe")

# search on google is https://www.naukri.com/
driver.get("https://www.naukri.com/hr-recruiters-consultants") 

# enter the value for designation Data Science
designation=driver.find_element(By.CLASS_NAME,"sugInp")
designation.send_keys("Data Science")
time.sleep(2)

# for click on search button
search=driver.find_element(By.XPATH,"//button[@class='fl qsbSrch blueBtn']")
search.click()
time.sleep(3) # this time is require to open site

#fetch all require data like name, company etc.
name=driver.find_elements(By.XPATH,'//span[@class="fl ellipsis"]')
Name=[i.text for i in name]

designation=driver.find_elements(By.XPATH,'//span[@class="ellipsis clr"]')
Designation=[i.text for i in designation]

company=driver.find_elements(By.XPATH,'//a[@class="ellipsis"][2]')
Company=[i.text for i in company]

skills_they_hire_for=driver.find_elements(By.XPATH,'//div[@class="hireSec highlightable"]')
Skills_they_hire_for=[i.text for i in skills_they_hire_for]

location=driver.find_elements(By.XPATH,'//small[@class="ellipsis"]')
Location=[i.text for i in location]

#creat Data Frame 
df=pd.DataFrame({
    'Name':Name[0:47],
    'Designation':Designation[0:47],
    'Company':Company[0:47],
    'Skills_they_hire_for':Skills_they_hire_for[0:47],
    'Location':Location[0:47]
})
df

,Name,Designation,Company,Skills_they_hire_for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
12,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
14,Vaishnavi Kudalkar,HR Executive,Codeachive learning,"Data Science, Python, Data Analytics",Mumbai
15,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Chandigarh
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
25,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
26,Deeparchi Sharma,Company Recruiter,ZIGRAM,"Research, Digital Marketing, Analytics, Softwa...",Gurgaon
27,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
28,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
29,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
30,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Delhi
31,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Bengaluru / Bangalore
32,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Mysoru / Mysore
33,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Hyderabad / Secunderabad
34,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Bengaluru / Bangalore
35,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",New Delhi
36,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Chennai
37,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Aligarh
38,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Salt Lake City
39,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Pune
40,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Bengaluru / Bangalore
41,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Mumbai
42,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Indore
43,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Bengaluru / Bangalore
44,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",MYSORE
45,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",Hyderabad / Secunderabad
46,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Bengaluru / Bangalore

Q6.Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [85]:
# connect to webdriver
driver=webdriver.Chrome(r"chromedriver.exe")
driver.maximize_window()

# search on google
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")


#Fetch Require Data
book_name=driver.find_elements(By.XPATH,'//div[@class="embed block"]/table/tbody/tr/td[2]')
Book_name=[i.text for i in book_name]

author_name=driver.find_elements(By.XPATH,'//div[@class="embed block"]/table/tbody/tr/td[3]')
Author_name=[i.text for i in author_name]

volumes_sold=driver.find_elements(By.XPATH,'//div[@class="embed block"]/table/tbody/tr/td[4]')
Volumes_sold=[i.text for i in volumes_sold]

publisher=driver.find_elements(By.XPATH,'//div[@class="embed block"]/table/tbody/tr/td[5]')
Publisher=[i.text for i in publisher]

genre=driver.find_elements(By.XPATH,'//div[@class="embed block"]/table/tbody/tr/td[6]')
Genre=[i.text for i in genre]

#Creat DataFrame
df=pd.DataFrame({
    'Book_name':Book_name,
    'Author_name':Author_name,
    'Volumes_sold':Volumes_sold,
    'Publisher':Publisher,
    'Genre':Genre
})
df

,Book_name,Author_name,Volumes_sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

Q7.Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [87]:
# connect to webdriver
driver9=webdriver.Chrome(r"chromedriver.exe")
driver9.maximize_window()

# search on google is https://www.imdb.com/list/ls095964455/
driver9.get("https://www.imdb.com/list/ls095964455/")


#Fetch all the require data like name,Year, etc.
name=driver9.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/a')
Name=[i.text for i in name]

year_span=driver9.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/span[2]')
Year_span=[i.text for i in year_span]

genre=driver9.find_elements(By.XPATH,'//p[@class="text-muted text-small"]/span[5]')
Genre=[i.text for i in genre]

run_time=driver9.find_elements(By.XPATH,'//p[@class="text-muted text-small"]/span[3]')
Run_time=[i.text for i in run_time]

ratings=driver9.find_elements(By.XPATH,'//div[@class="ipl-rating-star small"]/span[2]')
Ratings=[i.text for i in ratings]

votes=driver9.find_elements(By.XPATH,'//div[@class="lister-item-content"]/p[4]/span[2]')
Votes=[i.text for i in votes]


#Creat Data Frame
df=pd.DataFrame({
    'Name':Name,
    'Year_span':Year_span,
    'Genre':Genre,
    'Run_time':Run_time,
    'Ratings':Ratings,
    'Votes':Votes
})
df

,Name,Year_span,Genre,Run_time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,099,804"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,190,086"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"994,022"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"294,179"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"253,286"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"50,373"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"61,969"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"199,892"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"41,707"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"246,915"

Q8.Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code.

In [88]:
# connecting to webdriver
driver10=webdriver.Chrome(r"chromedriver.exe")
driver10.maximize_window()

# search on google
driver10.get("https://archive.ics.uci.edu/ml/index.php")


# searching for click
Click=driver10.find_element(By.XPATH,'/html/body/table[2]/tbody/tr/td/span/b/a')
Click.click()
time.sleep(3)


#fetch all require Data
dataset_name=driver10.find_elements(By.XPATH,'//table[@cellpadding="3"]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b')
Dataset_name=[i.text for i in dataset_name]

data_type=driver10.find_elements(By.XPATH,'//table[@cellpadding="3"]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]/p')
Data_type=[i.text for i in data_type]


task=driver10.find_elements(By.XPATH,'//table[@cellpadding="3"]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]/p')
Task=[i.text for i in task]

attribute_type=driver10.find_elements(By.XPATH,'//table[@cellpadding="3"]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]/p')
Attribute_type=[i.text for i in attribute_type]

no_of_instances=driver10.find_elements(By.XPATH,'//table[@cellpadding="3"]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]/p')
No_of_instances=[i.text for i in no_of_instances]

no_of_attribute=driver10.find_elements(By.XPATH,'//table[@cellpadding="3"]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]/p')
No_of_attribute=[i.text for i in no_of_attribute]

year=driver10.find_elements(By.XPATH,'//table[@cellpadding="3"]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]/p')
Year=[i.text for i in year]


#Creat DataFrame
df=pd.DataFrame({
    'Dataset_name':Dataset_name,
    'Data_type':Data_type[1:],
    'Task':Task[1:],
    'Attribute_type':Attribute_type[1:],
    'No_of_instances':No_of_instances[1:],
    'No_of_attribute':No_of_attribute[1:],
    'Year':Year[1:]
})
df

,Dataset_name,Data_type,Task,Attribute_type,No_of_instances,No_of_attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021